### ISSUE TITLE
Visualization of the regulatory network

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#18]
Hi I am planning to use networkx in python to visualize the GRN from bigSCale2. Can I use the results$graph directly with networkx if not how can I modify it for the same.

Thanks

**Comment by iaconogi** [comment]
Plotting of the networks.

For the images of the paper I did not use igraph but instead I used pajek (http://mrvar.fdv.uni-lj.si/pajek/).
The only "complication" is that you need to save your network in pajek format, which is essentially a text file with the list of edges and vertices along with additional options such as colors or sizes.
I cannot help you directly with the igraph to pajek export, because I did it in MATLAB using an old script of mine.
I think that igraph itselfs has a built-in export in pajek format, which you should teak if you want for example to highlight specific nodes with specific colors.
