### ISSUE TITLE
Error in Rfast::rowVars

### ISSUE THREAD

**Issue by Zhangruiqi111** [iaconogi/bigSCale2#36]
when I try the Gene Regulatory Networks tutorial , the first step "results.ctl=compute.network(expr.data = expr.ctl,gene.names = gene.names)" reported an error:  
Error in Rfast::rowVars(expr.row.sorted[, (num.samples - skwed.cells):num.samples],  : 
  unused argument (suma = NULL)

**Comment by JasonLiZhou** [comment]
Hi, I just ran into the same situation. After digging into the source code, I figured out the problem seems related to the updated Rfast package, as the 'suma' parameter has been deprecated ever since version 1.8.8. 
[https://github.com/iaconogi/bigSCale2/blob/master/R/Functions.R](url)
![image](https://github.com/iaconogi/bigSCale2/assets/11907573/f66b3abe-838c-4435-a052-230d237d3eb0)
[https://github.com/RfastOfficial/Rfast/blob/master/NEWS.md](url)
![image](https://github.com/iaconogi/bigSCale2/assets/11907573/1ae6b5db-92e4-43cf-a8cb-32dfacda1d9e)
So maybe you could try downgrading the Rfast package back to earlier versions.

**Comment by Zhangruiqi111** [comment]
Thank you very much for your answer！
