### ISSUE TITLE
raw fastq

### ISSUE THREAD

**Issue by bharati-mehani** [iaconogi/bigSCale2#8]

**Comment by iaconogi** [comment]
I cannot read anything

**Comment by bharati-mehani** [comment]
Sorry for the confusion.
Can BigScale2 deal with fastq files directly?

**Comment by iaconogi** [comment]
No, as most of the analysis tools also bigSCale2 starts from the matrix of expression counts.
You have to map the fastq first with a mapper.
I know only of one tool which does mapping and analysis which is SCATER, but I think it uses a psseudomapper which might be less accurate.

**Comment by bharati-mehani** [comment]
Thanks iaconogi for the clarification. I am planning to use data generated
by Smart-Seq2 protocol. For which I’ll use STAR aligner followed by HTSEQ
to generate the read count matrix.

I have few more queries as written below:

-Since bigSCale2 requires its input data in “sce” format for clustering,
how should I convert my count matrix into the same?

-And my another query is related to study Regulatory Network, Can I perform
this set of analysis only on tumor data as I don’t have the data from
control samples?


Thanks and regards
Bharati

**Comment by iaconogi** [comment]
-Since bigSCale2 requires its input data in “sce” format for clustering,
how should I convert my count matrix into the same?

**bigSCale2 uses single Cell Experiment only in the clustering and phenotyping tool. The network analysis works straight with the expression counts, as shown in the tutorial.**

_-And my another query is related to study Regulatory Network, Can I perform
this set of analysis only on tumor data as I don’t have the data from
control samples?

**You can. However, with only one conditoin you will not ba able to track changes in centrality. You will be able however to rank the nodes by centrality to find the most biologically important ones.**

Giovanni
